# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04e7d7f593cbdaf280ec4f73e2a51823f8fdb41fbed132ef38e16fa0b988eff8d32e5ea2094ebcf1aafe8b7ab5b5521b47d82ba6e116f9e8788e2a270463fb83

test:
  secret_key_base: c4ba309e5b0ce3b19c0c77003c1b488af9a44131d3c851f4fd3eec6f284d8f53bfe1381d2a73138656c343b2257bbf023ebf357a5375b5ca00bf8ef0ec829b87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
